<?php

namespace Database\Seeders;

use App\Models\Errand;
use App\Models\User;
use Illuminate\Database\Seeder;

class DemoErrandsSeeder extends Seeder
{
    public function run(): void
    {
        $sender = User::query()->where('email', 'sender@errandbridge.com')->first();

        if (! $sender) {
            return;
        }

        foreach (range(1, 5) as $index) {
            Errand::updateOrCreate(
                [
                    'sender_id' => $sender->id,
                    'title' => "Demo Lagos Errand {$index}",
                ],
                [
                    'description' => 'Auto-seeded errand for map visualization.',
                    'type' => 'delivery',
                    'status' => 'pending',
                    'pickup_address' => "Lagos Pickup {$index}",
                    'pickup_lat' => fake()->randomFloat(7, 6.4300000, 6.7000000),
                    'pickup_lng' => fake()->randomFloat(7, 3.2000000, 3.5500000),
                    'delivery_address' => "Lagos Delivery {$index}",
                    'delivery_lat' => fake()->randomFloat(7, 6.4300000, 6.7000000),
                    'delivery_lng' => fake()->randomFloat(7, 3.2000000, 3.5500000),
                    'budget_usdt' => fake()->randomFloat(2, 25, 200),
                    'notes' => 'Generated by DemoErrandsSeeder.',
                    'runner_id' => null,
                ]
            );
        }
    }
}
